services:

  foo-api:
    image: wiremock/wiremock:3.11.0
    ports:
      - "8080"
    command:
      - "--global-response-templating"
    volumes:
      - ./wiremock/foo-api:/home/wiremock

  bar-api:
    image: wiremock/wiremock:3.11.0
    ports:
      - "8080"
    command:
      - "--global-response-templating"
    volumes:
      - ./wiremock/bar-api:/home/wiremock
